#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clear old IC
rm -rf 0

# copy IC
mkdir 0
cp -rf 0.org/* 0

# create base mesh 
runApplication blockMesh
runApplication decomposePar
runParallel snappyHexMesh -overwrite
runApplication reconstructParMesh -constant -mergeTol 1 #-- for openfoam6

# create slipBC 
runApplication topoSet -dict system/topoSetDict.1
runApplication createPatch -overwrite

# decompose again
rm -rf processor*
mv log.decomposePar log.decomposePar2
runApplication decomposePar

# get the solver application
application=`getApplication`

# run the application
runParallel $application

